[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "pihole-speedtest-v6"
version = "1.0.2"
description = "Independent speed-test companion for Pi-hole v6"
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [{ name = "Nilesh Ramrattan" }]
dependencies = []

[project.scripts]
pihole-speedtest = "pihole_speedtest.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
pihole_speedtest = ["web/*"]
