services:
  pihole-speedtest:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8765:8765"
    volumes:
      - pihole-speedtest:/data
    restart: unless-stopped
volumes:
  pihole-speedtest: {}
